name: Update Contributors

on:
  push:
    branches: [master]
    paths:
      - 'src/**'
      - 'Cargo.toml'
      - '.github/workflows/**'
  pull_request_target:
    types: [closed]
    branches: [master]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-contributors:
    name: Update Contributors
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request_target' || github.event.pull_request.merged == true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update contributors
        uses: akhilmhdh/contributors-readme-action@v2.3.10
        with:
          filename: README.md
          placeholder: "<!-- CONTRIBUTORS-LIST:START -->"
          placeholder_end: "<!-- CONTRIBUTORS-LIST:END -->"
          columns_per_row: 6
          collaborators: true
          contributor_list: true
          use_username: false

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "docs: update contributors list [skip ci]"
            git push
          fi
